### PR TITLE
I added the new website

### PR DESCRIPTION
**Pull request by richcg**
Moved Old site to "Original_Website" folder.

### CODE REVIEW

**Comment by xeroc** [comment]
Since I don't own bitshares.org, I cannot say much about the webpage and what should be there etc.
However, I can tell you that the BitShares Blockchain Foundation is currently in discussions with Cryptonomex (current owner) to take over the site. If/After that has happend, there will be much work that needs to be done, not only on the design aspects, but also the presentation and content aspect.

The BBF has some plans for bitshares.org that it thinkgs need to be addresses. Mostly, bitshares.org needs a very precise description for investors about BitShares and the BTS token, as well as what the platform is good for. This content also requires some form of Terms&Conditions.

I personally don't think it is wise to update the webpge's content without prior legal consultation. And for the web design/layout, I would rather see the page be updated in a single shot (content+layout) to not confuse people, but that's my personal opinion.

**Comment by richcg** [comment]
Hi Fabian,

Thanks for your reply. In response to what you are saying:

*I personally don't think it is wise to update the webpge's content without
prior legal consultation. And for the web design/layout, I would rather see
the page be updated in a single shot (content+layout) to not confuse
people, but that's my personal opinion.*

I don't know if you are aware, but the new design is already done, you can
see it at http://is1.co
Also the wording on all pages is the same except for the home page. Stan
Larimer has seen it and said that he wants to go forward with it. Please
let me know if you still have the same opinion.

Thanks!



Richard
WebsiteGrafix
951-506-1196
www.websitegrafix.com

**Review by svk31 — CHANGES_REQUESTED** [review]
This just moves all of the old website to a new subfolder.

Where's the new website content? Is the new website content compatible with hosting on github pages?

The /wallet folder needs to remain and be accessible as before at bitshares.org/wallet for migration purposes.

**Comment by richcg** [comment]
I moved the wallet folder. It is now at bitshares.org/wallet. The website consists of html, css, and js files. I don’t know if they need to be converted to a different format so that they can be hosted on github.

**Comment by xeroc** [comment]
This needs to be brought to Stan Larimer's attention. He (CNX) is the owner of bitshares.org.

**Comment by abitmore** [comment]
This repository is being archived. The new repository is https://github.com/bitshares/bitshares.org

**Pull request closed without merging**
